return {
  name = "g++ build",
  builder = function()
    local infile = vim.fn.expand "%:p"
    local outfile = vim.fn.expand "%:p:r"
    return {
      cmd = { "g++" },
      args = {
        "-std=c++23",
        "-fanalyzer",
        "-fsanitize=address",
        "-fsanitize=undefined",
        "-O2",
        "-fno-omit-frame-pointer",
        "-g",
        "-fchar8_t",
        "-fcoroutines",
        "-flto",
        "-fuse-ld=mold",
        "-fmodules-ts",
        "-pipe",
        "-pedantic",
        "-Wall",
        "-Wcast-align=strict",
        "-Wcast-qual",
        "-Wconversion",
        "-Wctor-dtor-privacy",
        "-Wdouble-promotion",
        "-Wduplicated-branches",
        "-Wduplicated-cond",
        "-Wextra",
        "-Wfloat-equal",
        "-Wformat-overflow=2",
        "-Wformat=2",
        "-Winline",
        "-Winvalid-pch",
        "-Wlogical-op",
        "-Wmissing-noreturn",
        "-Wnon-virtual-dtor",
        "-Wnull-dereference",
        "-Wold-style-cast",
        "-Woverloaded-virtual",
        "-Wpacked",
        "-Wpedantic",
        "-Wshadow",
        "-Wsign-conversion",
        "-Wstack-protector",
        "-Wstrict-overflow=4",
        "-Wswitch-enum",
        "-Wundef",
        "-Wunused",
        "-Wuseless-cast",
        -- "-Werror",
        infile,
        "-o",
        outfile,
      },
      components = { { "on_output_quickfix", open = true }, "default" },
    }
  end,
  condition = {
    filetype = { "cpp" },
  },
}
