return {
  {
    "SmiteshP/nvim-navic",
    init = function()
      vim.g.navic_silence = true
    end,
    config = true,
  },
  {
    "utilyre/barbecue.nvim",
    name = "barbecue",
    dependencies = {
      "nvim-navic",
    },
    event = "VeryLazy",
    opts = {
      theme = "catppuccin",
      attach_navic = false,
      kinds = {
        Array = "",
        Boolean = "",
        Class = "ﴯ",
        Color = "",
        Constant = "",
        Constructor = "",
        Enum = "",
        EnumMember = "",
        Event = "",
        Field = "ﰠ",
        File = "",
        Folder = "",
        Function = "",
        Interface = "",
        Key = "",
        Keyword = "",
        Method = "",
        Module = "",
        Namespace = "",
        Null = "",
        Number = "",
        Object = "",
        Operator = "",
        Package = "",
        Property = "",
        Reference = "",
        Snippet = "",
        String = "",
        Struct = "פּ",
        Text = "",
        TypeParameter = "",
        Unit = "塞",
        Value = "",
        Variable = "",
      },
    },
  },
}
